### ISSUE TITLE
Solaris sudo issue

### ISSUE THREAD

**Issue by boomertsfx** [glensc/nagios-plugin-check_raid#101]
Solaris 10 doesn't have sudo stock.  I'm running check_raid.pl 3.2.3 from today as **root** on: 

```SunOS 5.10 Generic_141445-09 i86pc i386 i86pc```

```
root@dl180-009:[/var/tmp]# ./check_raid.pl -d
Can't find sudo at ./check_raid.pl line 91.
```

My temporary hack of ```find_sudo()``` to get it working is:
from: ```return \@sudo if @sudo;```
to: ```return \@sudo if (@sudo || $> == 0);```

Perhaps a command like flag or uid check can be done.  I'll leave it to you to decide on what's the best universal solution =)

Thanks!

**Comment by glensc** [comment]
so, how do you became root from nagios nrpe?
