### ISSUE TITLE
Error when running through nrpe

### ISSUE THREAD

**Issue by jangras** [glensc/nagios-plugin-check_raid#103]
```
[root@CLIENT01 libexec]# ./check_raid.pl
OK: megacli:[Volumes(1): NoName:Optimal; Devices(6): 12,13,10,09,11,08=Online]
[root@CLIENT01 libexec]# ./check_nrpe -H 172.30.0.46 -c check_raid.pl
OK: megacli:[Volumes(0): ; Devices(0): ]
```

**Comment by glensc** [comment]
bugreport fails to provide info according to [CONTRIBUTING.md](https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md)

**Comment by jangras** [comment]
[root@Logcon1 plugins]# sudo -u nagios /usr/lib64/nagios/plugins/check_raid.pl -V
check_raid Version 3.2.3

Sudo setup is ok. I ran check_raid.pl -S to setup sudo. all required sudo entries done by this command. Please help me to solve this. when running locally it is giving perfect output while running through nrpe below is the output 

nagios:/usr/lib/nagios/plugins # ./check_nrpe -H 10.10.30.186 -c check_raid
CRITICAL: megacli:[Volumes(0): ; Devices(0): ]
please help.

**Comment by jangras** [comment]
Hi Thanks ... you are right may be it is selinux problem as per below logs:

type=AVC msg=audit(1431406882.305:421206): avc:  denied  { execute_no_trans } for  pid=20929 comm="sh" path="/usr/lib64/nagios/plugins/check_raid.pl" dev=dm-9 ino=282538 scontext=unconfined_u:system_r:nrpe_t:s0 tcontext=unconfined_u:object_r:lib_t:s0 tclass=file
type=SYSCALL msg=audit(1431406882.305:421206): arch=c000003e syscall=59 success=yes exit=0 a0=1204c30 a1=12041c0 a2=1203620 a3=7fff6982b8b0 items=0 ppid=20928 pid=20929 auid=0 uid=496 gid=497 euid=496 suid=496 fsuid=496 egid=497 sgid=497 fsgid=497 tty=(none) ses=13020 comm="check_raid.pl" exe="/usr/bin/perl" subj=unconfined_u:system_r:nrpe_t:s0 key=(null)
type=USER_CMD msg=audit(1431406882.341:421207): user pid=20931 uid=496 auid=0 ses=13020 subj=unconfined_u:system_r:nrpe_t:s0 msg='cwd="/" cmd=2F7573722F7362696E2F4D656761436C69202D50444C697374202D61414C4C202D4E6F4C6F67 terminal=? res=failed'
type=USER_CMD msg=audit(1431406882.343:421208): user pid=20932 uid=496 auid=0 ses=13020 subj=unconfined_u:system_r:nrpe_t:s0 msg='cwd="/" cmd=2F7573722F7362696E2F4D656761436C69202D4C64496E666F202D4C616C6C202D61414C4C202D4E6F4C6F67 terminal=? res=failed'

can you please help me to solve this. i can not disable selinux at system level.

**Comment by glensc** [comment]
sorry, can't help with selinux. try [stackoverflow search](http://stackoverflow.com/questions/tagged/selinux)

**Comment by jangras** [comment]
Hey Glensc 
sorry it is not selinux. it is not using sudo when running though nrpe. check debug logs below:

May 12 18:05:06 backup nrpe[31293]: Host is asking for command 'check_raid' to be run...
May 12 18:05:06 backup nrpe[31293]: Running command: /usr/lib/nagios/plugins/check_raid.pl 2>&1
May 12 18:05:06 backup nrpe[31293]: Command completed with return code 3 and output: No RAID configuration found (tried: lsscsi, metastat, mdstat, megacli, ips, aaccli, afacli, mpt, gdth, dpt_i2o, tw_cli, arcconf, megarc, cmdtool2, cciss, hp_msa, sas2ircu, hpacucli, areca, dmraid)

**Comment by glensc** [comment]
well. i can't guess for you, show me ALL your configuration.

did you run plugin with `-d`? it's explained in CONTRIBUTING.md!

**Comment by ijunaidfarooq** [comment]
I am having the same issue ! Can you help @glensc

**Comment by glensc** [comment]
@ijunaidfarooq create issue and fill as much information you can
