### ISSUE TITLE
uninitialized value when battery is failed

### ISSUE THREAD

**Issue by lanord** [glensc/nagios-plugin-check_raid#105]
When the battery is failed got those error.

/usr/lib/nagios/plugins/check_raid
Use of uninitialized value in string ne at /usr/lib/nagios/plugins/check_raid line 2887.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/check_raid line 2889.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/check_raid line 2892.
Use of uninitialized value in numeric lt (<) at /usr/lib/nagios/plugins/check_raid line 2893.
Use of uninitialized value in numeric lt (<) at /usr/lib/nagios/plugins/check_raid line 2896.
Use of uninitialized value in numeric lt (<) at /usr/lib/nagios/plugins/check_raid line 2900.
Use of uninitialized value in numeric lt (<) at /usr/lib/nagios/plugins/check_raid line 2903.
Use of uninitialized value in numeric lt (<) at /usr/lib/nagios/plugins/check_raid line 2907.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/check_raid line 2908.
CRITICAL: arcconf:[Controller:Optimal, Battery Status: Failed, Battery Overtemp: , Battery Capacity Remaining: %, Battery Time: m, Logical Device 0(RAID10):Optimal, Drives: WD-WMATV3471115,WD-WMATV3047731,WD-WMATV3036928,WD-WMATV3086188=Online]

If you need more info do not hesitate.
Laurent Sauvé

**Comment by glensc** [comment]
yes of course, did you read CONTRIBUTING.md before opening this ticket?

**Comment by lanord** [comment]
Here is the data as per your request in CONTRIBUTING.md 

http://pastebin.com/SU2GBsJY

Hope this will help.

**Comment by glensc** [comment]
now prints:
```
Controller:Optimal, Battery Status: Failed, Logical Device 0(RAID10):Optimal, Drives: WD-WMATV3471115,WD-WMATV3047731,WD-WMATV3036928,WD-WMATV3086188=Online
```
