### ISSUE TITLE
Checks fail on HP H240ar

### ISSUE THREAD

**Issue by msmithbbc** [glensc/nagios-plugin-check_raid#106]
Checks fail on HP H240ar controller due to mode being returned (this card can do RAID or HBA modes).

```
DEBUG EXEC: /proc/mdstat at ./check_raid line 459.
DEBUG EXEC: /usr/sbin/hpssacli controller all show status at ./check_raid line 459.
DEBUG EXEC: /usr/sbin/hpssacli controller slot=0 (RAID Mode) logicaldrive all show at ./check_raid line 459.
UNKNOWN: hpacucli:[Smart HBA H240ar: ]
```

Proposed fix is to add:
`$slot =~ s/ \(RAID Mode\)//;`

Before or after:
`$slot =~ s/ \(Embedded\)//;`

Which gives the correct output:
```
root@box-x:/usr/lib/nagios/plugins# ./check_raid -d
check_raid Version 3.2.3
See CONTRIBUTING.md how to report bugs with debug data:
https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md

DEBUG EXEC: /proc/mdstat at ./check_raid line 459.
DEBUG EXEC: /usr/sbin/hpacucli controller all show status at ./check_raid line 459.
DEBUG EXEC: /usr/sbin/hpacucli controller slot=0 logicaldrive all show at ./check_raid line 459.
OK: hpacucli:[Smart HBA H240ar: Array A(OK)[LUN1:OK]]
```

I don't have another box or controller to check the output when the card is set to HBA mode.

**Comment by glensc** [comment]
please provide test data according to CONTRIBUTING.md

**Comment by msmithbbc** [comment]
martin@martinsmith:~/workspace/check_raid/nagios-plugin-check_raid$ perl t/check_hpacucli.t 
1..25
ok 1 - plugin created
ok 2 - check ran
ok 3 - status code set
ok 4 - status code matches
ok 5 - status message
ok 6 - plugin created
ok 7 - check ran
ok 8 - status code set
ok 9 - status code matches
ok 10 - status message
ok 11 - plugin created
ok 12 - check ran
ok 13 - status code set
ok 14 - status code matches
ok 15 - status message
ok 16 - plugin created
ok 17 - check ran
ok 18 - status code set
ok 19 - status code matches
ok 20 - status message
ok 21 - plugin created
ok 22 - check ran
ok 23 - status code set
ok 24 - status code matches
ok 25 - status message

**Comment by glensc** [comment]
Why are you posting me result of your test run? Please read CONTRIBUTING.md how to provide test DATA, of PLUGIN COMMANDS.

**Comment by msmithbbc** [comment]
Sorry about that, I got a bit confused.  I hope this is what you're after.

**These are the same before and after:**

DEBUG EXEC: /proc/mdstat at ./check_raid.pl line 459.

*cat /proc/mdstat*
```
Personalities : 
unused devices: <none>
```

DEBUG EXEC: /usr/sbin/hpacucli controller all show status at ./check_raid.pl line 459.

*/usr/sbin/hpacucli controller all show status*
```
Smart HBA H240ar in Slot 0 (Embedded) (RAID Mode)
   Controller Status: OK
```

**This is before the change:**
DEBUG EXEC: /usr/sbin/hpacucli controller slot=0 (RAID Mode) logicaldrive all show at ./check_raid.pl line 459.

*/usr/sbin/hpacucli controller slot=0 \(RAID Mode\) logicaldrive all show*
```
Error: Invalid target syntax. "(raid" is not a valid target. Type "help" for
       more details.
```

**This is after the change:**
DEBUG EXEC: /usr/sbin/hpacucli controller slot=0 logicaldrive all show at ./check_raid line 459.

*/usr/sbin/hpacucli controller slot=0 logicaldrive all show*
```
OK: hpacucli:[Smart HBA H240ar: Array A(OK)[LUN1:OK]]
```

**Comment by glensc** [comment]
logicaldrive output seems you pasted wrong output, you pasted check_raid output, not from the actual command

the outputs should be something like others:
https://github.com/glensc/nagios-plugin-check_raid/tree/master/t/data/hpacucli/issue98
https://github.com/glensc/nagios-plugin-check_raid/tree/master/t/data/hpacucli/PR94

**Comment by msmithbbc** [comment]
You're absolutely right, I messed up my copy and paste.  I've updated the comment.
