### ISSUE TITLE
UNKNOWN: cciss:[Plugin error] on Hewlett-Packard Company Smart Array Gen8 Controllers

### ISSUE THREAD

**Issue by henti-q** [glensc/nagios-plugin-check_raid#109]
check_raid used to work. We've build a new server and latest master and release both fail. See below.

```
[root@prd-qua-za-cx01 nagios-plugin-check_raid-3.2.3]# ./check_raid.pl -d
DEBUG EXEC: /sys/module/hpsa/refcnt at ./check_raid.pl line 452.
DEBUG EXEC: /proc/driver/cciss at ./check_raid.pl line 452.
DEBUG EXEC: >&2 /usr/bin/cciss_vol_status -v at ./check_raid.pl line 448.
DEBUG EXEC: /usr/bin/cciss_vol_status -V /dev/sg0 /dev/sg1 at ./check_raid.pl line 452.
cciss_vol_status: /dev/sg0: Unknown SCSI device.
UNKNOWN: cciss:[Plugin error]
```

All devices on this machine is under /dev/sd\* not /dev/sg*, specifically /dev/sdb

```
[root@prd-qua-za-cx01 nagios-plugin-check_raid-3.2.3]# ./check_raid.pl /dev/sdb
cciss_vol_status: /dev/sg0: Unknown SCSI device.
UNKNOWN: cciss:[Plugin error]
[root@prd-qua-za-cx01 nagios-plugin-check_raid-3.2.3]# cciss_vol_status /dev/sdb
/dev/sdb: (Smart Array P420i) RAID 1 Volume 0 status: OK. 
/dev/sdb: (Smart Array P420i) Enclosure D2220sb (S/N: ) on Bus 0, Physical Port 1I status: OK.
```

H

**Comment by glensc** [comment]
install `lsscsi` tool. also, you have not provided all command outputs like CONTRIBUTING.md tells you to do.

also `check_raid` takes extra argument like you specified `/dev/sdb` devices to IGNORE, not devices to CHECK.

**Comment by henti-q** [comment]
I installed the lsscsi tool .

Output changes to : 

# ./check_raid.pl -d
check_raid Version 3.2.3
See CONTRIBUTING.md how to report bugs with debug data:
https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md

command 'lsscsi list' not defined at ./check_raid.pl line 3254

# lsscsi list
cannot decode list as an integer

As to the additional output, please see below : 

# /usr/bin/cciss_vol_status -v
cciss_vol_status version 1.10

# /usr/bin/cciss_vol_status -V /dev/sg0 /dev/sg1
cciss_vol_status: /dev/sg0: Unknown SCSI device.
cciss_vol_status: Warning: unknown controller type 0x21bd103c
cciss_vol_status: /dev/sg1: Unknown controller, board_id = 0x21bd103c

**Comment by glensc** [comment]
ok, i'm able to reproduce missing `lsscsi list` command definition error

**Comment by glensc** [comment]
please retry with master branch (a2ed6bb) and share output of `check_raid -d` **and** each individual command.

**Comment by henti-q** [comment]
Hi again, 

```
# ./check_raid.pl -d
check_raid Version 3.2.3
See CONTRIBUTING.md how to report bugs with debug data:
https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md

DEBUG EXEC: /usr/bin/lsscsi -g at ./check_raid.pl line 459.
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
DEBUG EXEC: >&2 /usr/bin/cciss_vol_status -v at ./check_raid.pl line 455.
DEBUG EXEC: /usr/bin/cciss_vol_status -V /dev/sg1 at ./check_raid.pl line 459.
cciss_vol_status: Warning: unknown controller type 0x21bd103c
cciss_vol_status: /dev/sg1: Unknown controller, board_id = 0x21bd103c
```

This looks like a missing controller/board ID in cciss_vol_status. 

If confirmed I'll raise with with upstream as there is a patch in the OSS project that contains the ID's. 

H

**Comment by henti-q** [comment]
Just for completeness. 

```
# /usr/bin/lsscsi -g
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
[target0:0:0]type?   vendor?  model?           rev?  -         -
[target1:3:0]type?   vendor?  model?           rev?  -         -
[0:0:0:0]    disk    HP iLO   Internal SD-CARD 2.09  -         /dev/sg0
[1:3:0:0]    storage HP       P244br           1.34  -         /dev/sg1
```

```
# /usr/bin/cciss_vol_status -v
cciss_vol_status version 1.10
```

```
# /usr/bin/cciss_vol_status -V /dev/sg1
cciss_vol_status: Warning: unknown controller type 0x21bd103c
cciss_vol_status: /dev/sg1: Unknown controller, board_id = 0x21bd103c
```

H

**Comment by glensc** [comment]
`Just for completeness.` --- i asked you to provide **ALL** output, it's not for **completeness**, it's to be able to diagnose your issues here without access to your system!

**Comment by glensc** [comment]
you may try to `modprobe sg` module, maybe it will help.

can you give version of your `lsscsi` tool and running kernel version? and also are you using `cciss` or `hpsa` kernel module?

**Comment by glensc** [comment]
still waiting for your info.

current version of [lsscsi](http://sg.danny.cz/scsi/lsscsi.html) is 0.28 (2014112). altho it probably depends more on kernel version than the tool itself.

**Comment by henti-q** [comment]
Hi Glen, 

Sorry, got side-tracked at work. 

Bizarrely, it's now working. I must have made a mistake somewhere or mixed up machines. 

```
[root@prd-qua-za-cx01 nagios-plugin-check_raid-3.2.3]# ./check_raid.pl 
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
sdev_scandir_sort: left parse failed
Use of uninitialized value in concatenation (.) or string at ./check_raid.pl line 3581.
OK: cciss:[/dev/sdb(Smart Array P420i): Volume 0 (RAID 1): OK, Drives(12): 1I-1-1,1I-1-10,1I-1-11,1I-1-12,1I-1-2,1I-1-3,1I-1-4,1I-1-5,1I-1-6,1I-1-7,1I-1-8,1I-1-9=OK, /dev/sg2(): Enclosures: D2220sb: OK]
```

```
[root@prd-qua-za-cx01 nagios-plugin-check_raid-3.2.3]# lsscsi -V
version: 0.17  2006/2/6
```
Sorry for the run around. you can close this issue.

H

**Comment by glensc** [comment]
i see one warning in your output. could you report data from your system (see CONTRIBUTING.md), so i would able to handle that uninitialized value warning
