### ISSUE TITLE
harden sudoers rules/usage

### ISSUE THREAD

**Issue by calestyo** [glensc/nagios-plugin-check_raid#111]
Hey Elan.

Not sure whether I've had proposed this in the past already, and you just rejected it, but if not:
Could we perhaps try to harden the sudoers rules that check_raid kindly provides?

I think e.g. about the following cases:
1. General options:
I once went through the sudoers manpage and tried to come up with the most hardened Defaults, that still would allow the RAID tools to run.
# Permissions

Defaults: nagios-sensor authenticate, !setenv, !preserve_groups, !closefrom_override

```
#Execution Environment
Defaults: nagios-sensor env_reset, !env_file, always_set_home, set_home, set_logname, secure_path="/usr/bin:/bin", umask=0022

#Security
Defaults: nagios-sensor !requiretty, !pwfeedback, !visiblepw, !umask_override, !stay_setuid, closefrom=3, timestamp_timeout=0, !shell_noargs, runas_default=nobody, !root_sudo

#Miscellaneous
Defaults: nagios-sensor ignore_dot, !fast_glob

#Logging
Defaults: nagios-sensor mail_no_perms, mail_no_host

#Help
Defaults: nagios-sensor lecture=never, !path_info
```

So maybe one could give the above as additional suggestion to all rules?
1. Not using \* in rules
   I've seen that in some cases you use \* like in sas2ircu:
   "CHECK_RAID ALL=(root) NOPASSWD: $cmd \* STATUS",
   Securitywise this is bad, I'd propose to replace these occasions by e.g.:
   "CHECK_RAID ALL=(root) NOPASSWD: $cmd [[:digit:]] STATUS",
   "CHECK_RAID ALL=(root) NOPASSWD: $cmd [[:digit:]][[:digit:]] STATUS",
   "CHECK_RAID ALL=(root) NOPASSWD: $cmd [[:digit:]][[:digit:]][[:digit:]] STATUS",
   it looks ugly, I know, but given that nagios checks may be executed in less trustworthy manners, it seems worth it.
2. Trying to use less permissions where it's known that this is possible.
   For example I know that e.g. sas2ircu runs perfectly fine with just an EGID=root, which is at least a bit less than EUID=root.
   So instead of
   "CHECK_RAID ALL=(root) NOPASSWD: $cmd \* STATUS",
   we could just use:
   "CHECK_RAID ALL=(:root) NOPASSWD: $cmd \* STATUS",

4). Allow the user to specify the used user/group
That's kinda related to (3) above, for those people who want to restrict things even more:
Add options to check_raid that allow to specify the user:group that should be tried with sudo.
For example some RAID tools may just need to access /dev/somedevice which can have e.g. permissions like:
brw-r----- 1 root disk
If r would be enough that it would be awesome if one could say check_raid --runas :disk which then uses sudo in that way. :)
The only problem here is probably, that this would need to be specifiable per raid tool :-/, as different tools might need different settings.

I'm really bad in Perl (i.e. it's more like fuzzing - I enter  random characters till what I want happens ;) )... but perhaps you'd have some interest as well and so I thought better ask before trying anything unless you'd reject it anyway.

Cheers,
Chris.

**Comment by glensc** [comment]
you reported this before in #6, it was closed be cause two years of no feedback

**Comment by calestyo** [comment]
Sorry again, for having overseen the comments in #6,... of course on can use one's own sudo rules, but:
a) then others don't benefit from any hardenings, which I think would be worth it
Many of these RAID tools are closed source blobs, so as in the example of sas2ircu, I'd consider it an tiny improvement to just give them root group instead of root user.

b) As for that specific example, sas2ircu already working fine with just root group, I wouldn't know how to do that just by sudoers rules, as there is currently no way to set a default group, see http://bugzilla.sudo.ws/show_bug.cgi?id=709 .
So either that would need to be implemented in sudo,... or the invoker (check_raid) would need to invoke sudo accordingly.

**Comment by glensc** [comment]
not going to implement this myself. send PR
