### ISSUE TITLE
check_multi-like fancyness 

### ISSUE THREAD

**Issue by calestyo** [glensc/nagios-plugin-check_raid#112]
Hey.

This is probably just some long term idea for enhancement.

Right now, check_raid already supports to check multiple different types of controllers, for some of them even mutliple types of the same controller, multiple disks, RAID-volumes, batteries and so on...

All that is stuffed together into one status with details in the info field.

I think it would be awesome if check_raid could produce output like seen in those screenshots:
http://my-plugin.de/wiki/projects/check_multi/screenshot

There's still one overall status, but one can have many sub-statuses, even in a tree-hierarchy which would be very suitable for check_raid, e.g. 
- type of controller
  - instances of that type of controller
    - RAID-volume 0 for the current controller
      - disk 0 of that RAID
      - disk 1 of that RAID
      - etc
    - RAID-volume 1 for the current controller
      - ...
    - battery for the current controller

As you can read on the URL above, one can even do fancy things like hide/show the non-failing sub-statuses.

Cheers,
Chris.

**Comment by glensc** [comment]
you reported this before: #2, and i killed it as it's too big effort with little gain.

**Comment by glensc** [comment]
not going to implement this myself. you are welcome to send PR's first that unify the `sub parse` results in all plugins, then can think of interface to export the data.
