### ISSUE TITLE
State should be warning when rebuilding array

### ISSUE THREAD

**Issue by nycterent** [glensc/nagios-plugin-check_raid#113]
When rebuilding raid check returns OK, it sbould be warning at least.

**Comment by glensc** [comment]
cmon! which plugin??!

**Comment by glensc** [comment]
also, check_raid.pl has options  to tune few states:

        --noraid=STATE      Set status as STATE if RAID controller is found. Defaults to `UNKNOWN`
        --resync=STATE      Set status as STATE if RAID is in resync state. Defaults to `WARNING`
        --check=STATE       Set status as STATE if RAID is in check state. Defaults to `OK`

**Comment by nycterent** [comment]
hello, 

latest version from github hpssacli

i've tried with /usr/lib64/nagios/plugins/check_raid.pl --resync=CRITICAL and /usr/lib64/nagios/plugins/check_raid.pl --resync=WARNING - still got OK 

when will have this situation again - will provide more input, sorry.

**Comment by glensc** [comment]
seems you still did not read CONTRIBUTING.md? closing as i see you do not have any output for me to analyze.
