### ISSUE TITLE
hpssacli not registered by default (No RAID configuration found)

### ISSUE THREAD

**Issue by lordbaco** [glensc/nagios-plugin-check_raid#116]
--- check_raid.pl	2015-09-21 17:53:30.000000000 +0200
+++ check_raid.pl	2015-09-22 09:14:16.573050675 +0200
@@ -4379,6 +4379,9 @@
 # with the only difference that different program name is used
 use base 'hpacucli';
 
+# register
+push(@utils::plugins, __PACKAGE__);
+
 sub program_names {
 	qw(hpssacli);
 }

**Comment by glensc** [comment]
btw, you can make pull requests from githu8b web, just navitagte to the file and press edit. no need to paste diffs as  comment, which is hard for you to make and hard for me to merge.

btw, probably problem came from #114
