### ISSUE TITLE
check-raid.pl checks BBU for arcconf cards even when $bbu_monitoring = 0

### ISSUE THREAD

**Issue by giganteous** [glensc/nagios-plugin-check_raid#117]
Hello Glen,

https://github.com/glensc/nagios-plugin-check_raid/blob/master/check_raid.pl#L2425

Whilst I do think a failing BBU is something to alert for, there is a discrepancy between different raid cards on when to alert.

I would patch that line to contain an extra check against the global setting:

```diff
-			$this->critical if $c->{bbu} ne 'OK';
+			$this->critical if $c->{bbu} ne 'OK' && $this->bbu_monitoring;
```

Thanks for your time, and for maintaining this plugin.

**Comment by glensc** [comment]
great sight. although the `bbu_monitoring` flag was added because it was unstable in certain plugins. in `tw_cli` i was able to verify it myself and therefore it was present there unconditionally.
