### ISSUE TITLE
LD_LIBRARY_PATH for arcconf

### ISSUE THREAD

**Issue by lausser** [glensc/nagios-plugin-check_raid#119]
The arcconf utility needs libstdc++.so.5 which can be found in /usr/StorMan (next to arcconf).
So you Need to set LD_LIBRARY_PATH=/usr/StorMan. After playing around with sudo and preservation of user-space environment variables, i gave up.
LD_LIBRARY_PATH=/usr/StorMan sudo /usr/bin/ldd /usr/StorMan/arcconf
LD_LIBRARY_PATH=/usr/StorMan sudo -E /usr/bin/ldd /usr/StorMan/arcconf
nothing works...and it even requires setting LD_LIBRARY_PATH inside the plugin.
The most cleanest way i found was:

`$ cat <<EOLDSO > /etc/ld.so.conf.d/check_raid.conf`
`# arcconf location`
`/usr/StorMan`
`EOLDSO`

`$ ldconfig`

Gerhard

**Comment by glensc** [comment]
or symlink `libstdc++.so.5` to `/usr/lib` (`/usr/lib64`)

**Comment by glensc** [comment]
as for sudo part,

```
Defaults !env_reset
```

or
```
Defaults env_keep += LD_LIBRARY_PATH
```

**Comment by lausser** [comment]
I tried both with no success (Debian8). Unfortunately, because this would be the ideal solution, add these statements to the automatically generated sudoers-file and prepend the Nagios command_line with LD_LIBRARY_PATH=....

I have no idea why these flags don't work, it may be because of security concerns: http://serverfault.com/questions/371630/how-to-configure-sudoers-to-always-keep-ld-library-path-envrionment-variable

 

Gerhard

 

Von: Elan Ruusamäe [mailto:notifications@github.com] 
Gesendet: Montag, 28. September 2015 15:44
An: glensc/nagios-plugin-check_raid <nagios-plugin-check_raid@noreply.github.com>
Cc: Gerhard Lausser <Gerhard.Lausser@consol.de>
Betreff: Re: [nagios-plugin-check_raid] LD_LIBRARY_PATH for arcconf (#119)

 

as for sudo part,

Defaults !env_reset

or

Defaults env_keep += LD_LIBRARY_PATH

**Comment by glensc** [comment]
no, i will not add such hacks to check_raid. complain to arcconf support that the make proper installation package.

as for my personal suggestion, i suggest to put libstdc++.so.5 to standard library path (/usr/lib or /usr/lib64). some distributions contain "compat" packages for that.
