### ISSUE TITLE
UNKNOWN Dynamic Smart Array B140i hpssacli

### ISSUE THREAD

**Issue by thaonv** [glensc/nagios-plugin-check_raid#139]
Hi all,
HP Smart array B140i running ok but check_raid.pl show unknow ?

```
[root@******]# /usr/local/nagios/libexec/check_raid.pl --plugin hpssacli -d
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

DEBUG EXEC: /usr/sbin/hpssacli controller all show status at /usr/local/nagios/libexec/check_raid.pl line 474.
DEBUG EXEC: /usr/sbin/hpssacli controller slot=0b logicaldrive all show at /usr/local/nagios/libexec/check_raid.pl line 474.
UNKNOWN: hpssacli:[Dynamic Smart Array B140i: Array A(OK)[LUN1:OK]]
```

```
[root@****]# /usr/sbin/hpssacli controller slot=0b logicaldrive all show

Dynamic Smart Array B140i in Slot 0b

   array A

      logicaldrive 1 (465.7 GB, RAID 1, OK)

```

Can you help me??
Thanks very much!

**Comment by glensc** [comment]
please read the reporting bugs link. not all output given here!

**Comment by rajo** [comment]
Same issue here. Output:
`[root@xxx ~]# /usr/lib64/nagios/plugins/check_raid --plugin=hpssacli -d
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

DEBUG EXEC: /sbin/hpssacli controller all show status at /usr/lib64/nagios/plugins/check_raid line 474.
DEBUG EXEC: /sbin/hpssacli controller slot=0b logicaldrive all show at /usr/lib64/nagios/plugins/check_raid line 474.
UNKNOWN: hpssacli:[Dynamic Smart Array B140i: Array A(OK)[LUN1:OK]]
[root@xxx ~]# /sbin/hpssacli controller all show status

Dynamic Smart Array B140i in Slot 0b
   Controller Status: OK


[root@xxx ~]# /sbin/hpssacli controller slot=0b logicaldrive all show

Dynamic Smart Array B140i in Slot 0b

   array A

      logicaldrive 1 (10.9 TB, RAID 5, OK)

[root@xxx ~]#`

Thanks for your help!

**Comment by glensc** [comment]
the problem seems to be  that slot is named `0b`, it is not numeric

[the current code](https://github.com/glensc/nagios-plugin-check_raid/blob/4.0.2/lib/App/Monitoring/Plugin/CheckRaid/Plugins/hpacucli.pm#L59) requires it to be numeric.

i'll add alphanumeric support there, but any ideas where to get valid slot names? i.e how to validate that slot name is valid?

**Comment by glensc** [comment]
it was added in 07a240cd to handle invalid situations.

perhaps i verify just that the slot starts with digit?
