### ISSUE TITLE
Arcconf: don't mix drives with logical devices

### ISSUE THREAD

**Issue by fabricat** [glensc/nagios-plugin-check_raid#140]
In the status line you are pushing some strings like the following one:

> Failed/Degraded/Offline/etc **drives**:$c->{**logical**_failed/degraded/offline/etc}

Isn't this a bit confusing?
We are talking about **logical devices**, and not physical drives.
I'd suggest to replace the descriptive string.

Moreover the message "Degraded drives" appears **twice**!!!

**Comment by glensc** [comment]
please see CONTRIBUTING.md and provide test data.

**Comment by glensc** [comment]
Unable understand what he talks about; No test data; No output; No code references; Nothing.

**Comment by fabricat** [comment]
I'm sorry for the late response.

The code I was talking about is in /lib/App/Monitoring/Plugin/CheckRaid/Plugins/arcconf.pm, raw 495
The "failed drives" strings makes me think to a physical drive, not a logical device.
I would change it to "failed logical devices" and, if it is available, would add a physical HDDs status report.

About the duplicate degraded report, I've seen ti has been already fixed [here](https://github.com/glensc/nagios-plugin-check_raid/commit/6740bf8ca4b7c1416b10ab95d3981108edebe212).

Thank you.
