### ISSUE TITLE
Nagios3 server reports check_raid UNKNOWN - No active plugins (No RAID found) 

### ISSUE THREAD

**Issue by hitorchi** [glensc/nagios-plugin-check_raid#144]
I've been using 4.0.2 with an Ubuntu VM as my Nagios3 Server with the NRPE plugin and a Fedora machine (where 4.0.2 is installed in /usr/lib64/nagios/plugins) as the remote host with the NRPE server and Nagios plugins installed. The RAID controller is LSI MegaRAID SAS 9271-4i and I'm using MegaCLI located in my /opt/MegaRAID/MegaCLI folder.

On my Fedora machine, running check_raid.pl works fine giving:
`OK: megacli:[Volumes(1): DISK0.0:Optimal,WriteCache:DISABLED; Devices(2): 05,04=Online]
`
but on the nagios webpage on my Ubuntu VM the check_raid service’s status shows up as:
`NRPE: Unable to read output`
OR
`check_raid UNKNOWN – No active plugins (No RAID found)`

I've attempted to remedy the issue through modifying the sudoer file (in /etc/sudoers) and changing individual file permissions, but nothing seems to fix the issue.

**Image running check_raid.pl locally on Fedora machine:**
![capture 2](https://cloud.githubusercontent.com/assets/16524900/16499370/20b2110e-3ece-11e6-9133-55c87a82a85d.PNG)

**Image running check_raid.pl remotely with the NRPE plugin from Ubuntu VM :**
![capture](https://cloud.githubusercontent.com/assets/16524900/16499369/20ae0e24-3ece-11e6-8b1d-d1cf5bd86b3e.PNG)

I've looked through similar closed issues on the repo but have yet to find a solution.

**Comment by hitorchi** [comment]
My somewhat novice status with Linux was probably the real issue here, the solution is to disable SELinux in /etc/selinux/config and reboot the machine.

**Comment by glensc** [comment]
Run the plugin as same user your nagios is running, not root!

    sudo -H -u nagios /full/path/to/script.pl -d

it should give you glues what commands or files it is attempting to execute and what fails

**Comment by glensc** [comment]
Unable to solve; User gone; No feedback;
