### ISSUE TITLE
Can't locate object method "new" via package "Monitoring::Plugin"

### ISSUE THREAD

**Issue by Cholipen** [glensc/nagios-plugin-check_raid#147]
Hi,

I just downloaded this plugin in order to link it with Eyes of network 4.2 (Nagios Core 3.5.1).

I encountered a few problems concerning libs and such but got it fixed. Now the problem seems like perl don't find the package Monitoring::Plugin which is strange because the use Monitoring::Plugin at the beginning of the check_raid.pl which is supposed to verify it, right? Or it would cancel the script if not found.

I'm just only beginning with perl so please correct me if I'm talking nonsense.

Anyway, I just had to modify the following lines of the check_raid.pl in order to get it to start :
#!/usr/bin/perl
use lib '/home/nagios/nagios-plugin-check_raid-master/lib/App';
use Monitoring::Plugin@0.37;
use Monitoring::Plugin::CheckRaid;
use Monitoring::Plugin::CheckRaid::Sudoers;
use Monitoring::Plugin::CheckRaid::Plugin;
use Monitoring::Plugin::CheckRaid::Utils;

It is now starting but I got the following error :

# ./check_raid.pl -S
Subroutine program_names redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 37.
Subroutine commands redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 42.
Subroutine sudo redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 49.
Subroutine new redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 54.
Subroutine active redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 99.
Subroutine status redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 112.
Subroutine set_critical_as_warning redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 121.
Subroutine warning redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 127.
Subroutine critical redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 135.
Subroutine unknown redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 143.
Subroutine ok redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 150.
Subroutine resync redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 158.
Subroutine check_status redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 166.
Subroutine spare redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 174.
Subroutine bbulearn redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 182.
Subroutine cache_fail redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 190.
Subroutine bbu_monitoring redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 197.
Subroutine message redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 207.
Subroutine perfdata redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 217.
Subroutine longoutput redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 227.
Subroutine join_status redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 243.
Subroutine valid redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 261.
Subroutine format_bytes redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 276.
Subroutine nosudo_cmd redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 296.
Subroutine cmd redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Plugin.pm line 318.
Subroutine which redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Utils.pm line 26.
Subroutine find_sudo redefined at /home/nagios/nagios-plugin-check_raid-master/lib/App/Monitoring/Plugin/CheckRaid/Utils.pm line 36.
Can't locate object method "new" via package "Monitoring::Plugin" (perhaps you forgot to load "Monitoring::Plugin"?) at ./check_raid.pl line 16.

Line 16 corresponding to these : 

my $mp = Monitoring::Plugin->new(
        usage =>
                "Usage: %s [-h] [-V] [-S] [list of devices to ignore]",

        version => $VERSION,
        blurb => join($/,
                "This plugin checks all RAID volumes (hardware and software) that can be identified",
                "",
                "Homepage: $URL",
                "Reporting Bugs: $BUGS_URL",
        ),

        plugin  => $PROGNAME,
        shortname => $PROGNAME,
);

I made sure I had downloaded the right version of Monitoring::Plugin by using the following command : cpanm  Monitoring::Plugin@0.37

What did I do wrong?

Thanks a lot for your responses

Thomas

**Comment by glensc** [comment]
how did you download it? exact url please?

seems you did not download release version as described in README:
https://github.com/glensc/nagios-plugin-check_raid#installing

but rather unreleased dev version

neither i can figure out how you ran the code if you used git checkout:
https://github.com/glensc/nagios-plugin-check_raid#development

i.e what command did exactly do you run

the release version of this plugin is self contained, you do not need to modify any file or install dependencies.

**Comment by Cholipen** [comment]
Hey,

Thanks for your response, and sorry for mine's almost 3 weeks late, was on vacation...
I checked what you told me and I indeed did download the dev version (with git).

Downloaded the 4.0.2 realease and got the same lib issue, but after updating the path, it seems to work fine :)
Thanks a lot and once again, sorry.

Thomas

**Comment by glensc** [comment]
err, wtf. i think you still downloaded wrong version. exact url please, which i already asked!

**Comment by Cholipen** [comment]
Alright, here's the exact infos :
link from where I downloaded the script : https://github.com/glensc/nagios-plugin-check_raid/archive/4.0.2.tar.gz

actions done :
`tar xvf` of the archive into the user's home directory
then
```
[root@eon nagios-plugin-check_raid-4.0.2]# ./check_raid.sh
Can't locate Monitoring/Plugin.pm in @INC (@INC contains: /home/nagios/nagios-plugin-check_raid-4.0.2/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/nagios/nagios-plugin-check_raid-4.0.2/bin/check_raid.pl line 2.
BEGIN failed--compilation aborted at /home/nagios/nagios-plugin-check_raid-4.0.2/bin/check_raid.pl line 2.

```
if I verify : 

```
 ls /home/nagios/nagios-plugin-check_raid-4.0.2/lib/App/Monitoring/Plugin/CheckRaid
Plugin.pm  Plugins  SerialLine.pm  Sudoers.pm  Utils.pm
```
the problem seems to be coming from the script looking for Plugin.pm in: 
```
home/nagios/nagios-plugin-check_raid-4.0.2/lib
```
when it's in 
```
/home/nagios/nagios-plugin-check_raid-4.0.2/lib/App/Monitoring/Plugin/CheckRaid
```

I hope that it's what you wanted from me :)

If you want me to do specific actions, please tell me

**Comment by Cholipen** [comment]
Right, that's it :) Will know next time, thx for your patience and advices...

I'll download it right away

**Comment by glensc** [comment]
the error you are getting: `Monitoring/Plugin.pm` is not part of this program (see CPAN: [Monitoring::Plugin](http://search.cpan.org/~nierlein/Monitoring-Plugin-0.39/)), so there's nothing to fix in code. `App/Monitoring/Plugin/CheckRaid/Plugin.pm` is totally different module (part of this project)

if you wish to run the plugin using source code, you must install dependencies listed in `cpanfile` manually. easiest is probably just to do it with [cpanminus](https://github.com/miyagawa/cpanminus):

```
$ cpanm --installdeps -n .
```

**Comment by Cholipen** [comment]
Yes, it makes sense... Oh, all right, it'll be cleaner than what I did haha

thx a lot for all these infos :)

**Comment by glensc** [comment]
oh, and `info` is uncountable, always spelled as `info`, never `info` or `informations`

http://dictionary.cambridge.org/grammar/british-grammar/nouns-countable-and-uncountable

:D

**Comment by Cholipen** [comment]
mmmmmmh, damn. I wrote too fast :D
