### ISSUE TITLE
UNKNOWN: hpacucli:[Plugin error]

### ISSUE THREAD

**Issue by PitoneMaledetto** [glensc/nagios-plugin-check_raid#148]
Hi,
I am running successfully the plugin (4.0.2) using the hpacucli  8.60 and it seems the problem exist when running the plugin under hpacucli 9.1 (but maybe is nothing to do with the version of hpacucli).

**Locally:**
someuser@someserver:/usr/lib/nagios/plugins$ ./check_raid -p hpacucli
OK: hpacucli:[Smart Array P410i: Array A(OK)[LUN1:OK], Array B(OK)[LUN2:OK], Array C(OK)[LUN3:OK]]

**and:**
someuser@someserver:/usr/lib/nagios/plugins$ ./check_raid -d -p hpacucli
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

DEBUG EXEC: /usr/bin/sudo -A /usr/sbin/hpacucli controller all show status at ./check_raid line 474.
sudo: no askpass program specified, try setting SUDO_ASKPASS
UNKNOWN: hpacucli:[Plugin error]

**Remotely using NRPE:**
someuser@nagios-server:/usr/local/nagios/etc/objects# ../../libexec/check_nrpe -H xx.xx.xx.xx -c check_raid_infra -a hpacucli
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

**check_raid UNKNOWN - No active plugins (No RAID found)**

Just to say that in the working NRPE check_raid I don't specify the -u and it works just by running the ./check_raid -S the very first time to get the correct permission in the sudoers file.

Any help appreciated.
Thanks

**Comment by PitoneMaledetto** [comment]
Notice the difference in the sudoers file:

not working one:
# Lines matching CHECK_RAID added by ./check_raid -S on Mon Sep 12 10:59:56 2016
User_Alias CHECK_RAID=nagios
Defaults:CHECK_RAID !requiretty
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status --noflush
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status

working one:
# Lines matching CHECK_RAID added by ./check_raid -S on Fri Aug 26 15:30:29 2016
User_Alias CHECK_RAID=nagios
Defaults:CHECK_RAID !requiretty
CHECK_RAID ALL=(root) NOPASSWD: /usr/sbin/hpacucli controller all show status
CHECK_RAID ALL=(root) NOPASSWD: /usr/sbin/hpacucli controller * logicaldrive all show

not sure why hpacucli was not setup.....maybe because I have installed the hpacucli after I run ./check_raid -S

need to replicate this again.

**Comment by PitoneMaledetto** [comment]
Yes I have edited /etc/sudoers.d/check_raid with the correct lines and now it works.
Not sure if you would like to keep this thread for other people to read or delete it.
Thank you anyway.
Great plugin!

**Comment by glensc** [comment]
you can close bugs you reported by your own in github!

**Comment by PitoneMaledetto** [comment]
Yes, my question was if you would like for me to keep it open for other people to see just in case they have the same question/issue.

**Comment by glensc** [comment]
i think this can be closed, closed tickets are also searchable!

**Comment by glensc** [comment]
also, you can run `check_raid -S` over again, it should overwrite previous `/etc/sudoers.d/check_raid`
