### ISSUE TITLE
sudo: parse error in /etc/sudoers.d/check_raid near line 3

### ISSUE THREAD

**Issue by coronadouglass** [glensc/nagios-plugin-check_raid#153]
Hi, 
I tried to add check_raid.pl as a nagios check, but I get the following error on the server : 

```
./check_nrpe -H hostname -t 300 -c check_raid
CRITICAL: megacli:[Volumes(0): ; Devices(0): ]
```

From Nagios server, this works,  " !requiretty" : 
`ssh -t Hostname /usr/local/sbin/check_raid.pl -p megacli`

On the host it works, 
```
/usr/local/sbin/check_raid.pl --bbu-monitoring -p megacli
OK: megacli:[Volumes(1): DISK0.0:Optimal; Devices(4): 02,03,00,01=Online; Batteries(1): 0=Optimal] | Battery0_T=37;;;; Battery0_V=4057;;;;
Battery0:
 - State: Optimal
 - Charging status: None
 - Learn cycle requested: Yes
 - Learn cycle active: No
 - Missing: No
 - Replacement required: No
 - About to fail: No
 - Temperature: OK (37 C)
 - Voltage: OK (4057 mV)
```

But If I run with the nagios user : 
```
sudo -u nagios /usr/local/sbin/check_raid.pl --bbu-monitoring -p megacli
sudo: parse error in /etc/sudoers.d/check_raid near line 3
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

After ran this command, all my services pop as CRITICAL, I think it is because the error on the /etc/sudoers.d/check_raid file.  I had to remove this file  to remove the alerts on Nagios. 

```
./check_raid.pl -S
Updating file /etc/sudoers.d/check_raid
/etc/sudoers.d/check_raid.new.18720: parsed OK
/etc/sudoers.d/check_raid file updated.
check_raid OK - sudoers updated
```

```
./check_raid.pl -S -d
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

Content to be inserted to sudo rules:
--- sudoers ---

# Lines matching CHECK_RAID added by ./check_raid.pl -S on Thu Nov 10 23:31:17 2016
User_Alias CHECK_RAID=nagios
Defaults:CHECK_RAID !requiretty
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status --noflush
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -PDList -aALL -NoLog
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -LdInfo -Lall -aALL -NoLog
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -AdpBbuCmd -GetBbuStatus -aALL -NoLog
--- sudoers ---
check_raid OK - sudoers updated
```

Everything looks fine, same syntax than other servers, except that on this server I am using check_megaraid_sas, that works, but I would like to remove it and change it by  check_raid.pl

Sudoers file is corrupted ? Is there something that I miss ? 

Thank you for your help.

**Comment by glensc** [comment]
i don't know why your sudo does not like this line:
```
User_Alias CHECK_RAID=nagios
```

or at least i assume that is line 3, because your actual file with line numbers is not shown here.

you didn't even give what platform or sudo version you have

**Comment by glensc** [comment]
your problem is sudo related, find the problem (google, stackoverflow) and come back so can know how to fix in check_raid side.

meanwhile you can just setup check raid to run as root in your nrpe config:

```
command[check_nrpe]=/usr/bin/sudo /usr/lib/nagios/check_raid
```
