### ISSUE TITLE
support hpssacli

### ISSUE THREAD

**Issue by calestyo** [glensc/nagios-plugin-check_raid#161]
Hey.

It would be nice if hpssacli, which allows querying HP Smart Array Controllers could be supported.

The older already working tool hpacucli, seems to be disfunctional on newer kernels.
Even with hacks reported on the web (using uname26, respectively setarch --uname26) it doesn't work anymore on current Debian kernels (i.e. since jessie).

Fortunately, hpssacli seems to have the same commands/outpu as hpacucli had.
check_raid seems to work, by just creating a symlink from hpssacli to hpacucli.
So I'd guess it's enough to simply add the new name to have it working out of the box (packages from HP seem to install it to /usr/sbin/hpssacli (well actually that's just a wrapper script, which calls the actual binary).

This would be the output (including newlines) from the new tool as produced by the commands check_raid shows to call in -d(ebug) mode on the old tool:
```
# /usr/local/sbin/hpacucli controller all show status

Smart Array P840ar in Slot 0 (Embedded)
   Controller Status: OK
   Cache Status: OK
   Battery/Capacitor Status: OK


# /usr/local/sbin/hpacucli controller slot=0 logicaldrive all show

Smart Array P840ar in Slot 0 (Embedded)

   array A

      logicaldrive 1 (111.8 GB, RAID 1, OK)

   array B

      logicaldrive 2 (72.8 TB, RAID 6, OK)

# 

```

If you'd need further debug output, don't hesitate to ask.

Cheers,
Chris.

**Comment by glensc** [comment]
i do not understand why or what are you reporting. `hpssacli` is supported.
