### ISSUE TITLE
check_raid UNKNOWN - No active plugins (No RAID found)

### ISSUE THREAD

**Issue by afadli** [glensc/nagios-plugin-check_raid#163]
I ran `./check_raid.pl -S` as root and `/etc/sudoers.d/check_raid` is created.
running `sudo -u nagios  /usr/lib64/nagios/plugins/check_raid.pl -p megacli` locally gave me : 
```
check_raid UNKNOWN - No active plugins (No RAID found)
```

and run it like
```
# sudo -u nagios  /usr/lib64/nagios/plugins/check_raid.pl -p megacli -d 
check_raid 4.0.5
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs
check_raid UNKNOWN - No active plugins (No RAID found)
```

**Comment by afadli** [comment]
found out that if i : 
sudo -u nagios /usr/lib64/nagios/plugins/check_raid.pl -l 
i get only 1 active pluging 
dm 

but i need to use megacli, what am i missing

**Comment by glensc** [comment]
does the `-p megacli` work when ran as root? and the support tools are installed?

```
# which MegaCli64 MegaCli megacli
```
