### ISSUE TITLE
SUDO_ASKPASS when using with Icinga instead of Nagios

### ISSUE THREAD

**Issue by mchlrv** [glensc/nagios-plugin-check_raid#171]
When using the plugin with Icinga instead of Nagios an error is displayed: "sudo: no askpass program specified, try setting SUDO_ASKPASS" even when running "check_raid.pl -S".

To resolve this edit "/etc/sudoers.d/check_raid" and edit the first config line to "User_Alias CHECK_RAID=icinga".

It would be helpful to be able to specify a username when running "check_raid.pl -S".

**Output of `check_raid -d`:**

```
check_raid 4.0.7
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

DEBUG EXEC: /proc/mdstat at /opt/monitoring/plugins/check_raid.pl line 482.
DEBUG EXEC: /sbin/dmsetup status --noflush at /opt/monitoring/plugins/check_raid.pl line 482.
DEBUG EXEC: /opt/MegaRAID/MegaCli/MegaCli64 -PDList -aALL -NoLog at /opt/monitoring/plugins/check_raid.pl line 482.
DEBUG EXEC: /opt/MegaRAID/MegaCli/MegaCli64 -LdInfo -Lall -aALL -NoLog at /opt/monitoring/plugins/check_raid.pl line 482.
UNKNOWN: dm:[No devices to check]; megacli:[Volumes(2): vps-ssd10:Optimal,vps-data10:Optimal; Devices(6): 00,01,02,03,04,05=Online]
```

**Output of each command from `check_raid -d`**

**Comment by glensc** [comment]
so, under icinga, the plugin is ran with `icinga` user, not `nagios` user?

also, could you please post contents of your `/etc/sudoers.d/check_raid`

**Comment by mchlrv** [comment]
That is correct, it is running with `icinga` user.

Here is the output of `/etc/sudoers.d/check_raid`

`# Lines matching CHECK_RAID added by /opt/monitoring/plugins/check_raid.pl -S on Fri Jul 21 13:37:58 2017
User_Alias CHECK_RAID=icinga
Defaults:CHECK_RAID !requiretty
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status --noflush
CHECK_RAID ALL=(root) NOPASSWD: /sbin/dmsetup status
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -PDList -aALL -NoLog
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -LdInfo -Lall -aALL -NoLog
CHECK_RAID ALL=(root) NOPASSWD: /opt/MegaRAID/MegaCli/MegaCli64 -AdpBbuCmd -GetBbuStatus -aALL -NoLog`

**Comment by glensc** [comment]
i tried to add duplicate line, but that results syntax error:

```
User_Alias CHECK_RAID=icinga
User_Alias CHECK_RAID=nagios
```

however, if using comma, does it work for you?

```
User_Alias CHECK_RAID=icinga, nagios
```

**Comment by mchlrv** [comment]
It indeed works perfect, I now have:
`User_Alias CHECK_RAID=nagios,icinga`
