### ISSUE TITLE
add sensu to list of sudoers users

### ISSUE THREAD

**Issue by nschmalenberger** [glensc/nagios-plugin-check_raid#178]
https://github.com/glensc/nagios-plugin-check_raid/blob/6f72349ab92c1fa9ea7324c2effa7443f3a843e1/lib/App/Monitoring/Plugin/CheckRaid/Sudoers.pm#L41

Hi, I'm using check_raid.pl with sensu and for my systems that use megacli it needs to use sudo. Running check_raid -S and then manually editing the /etc/sudoers.d/check_raid to allow the sensu user to run megacli with sudo works great. Can you please add this to the list of sudo users? Thanks!

**Comment by glensc** [comment]
sorry, what is sensu and whats the unix login in question?

**Comment by nschmalenberger** [comment]
Sorry, sensu is another monitoring software: https://sensuapp.org/docs/1.0/overview/what-is-sensu.html <https://sensuapp.org/docs/1.0/overview/what-is-sensu.html> and it is compatible with nagios style plugins:
https://sensuapp.org/docs/1.0/overview/what-is-sensu.html#service-checks <https://sensuapp.org/docs/1.0/overview/what-is-sensu.html#service-checks>

The unix login is ‘sensu’. Thanks!
-Nick
