### ISSUE TITLE
arcconf: doesn't handle logical device status: Impacted (Build/Verify with fix : 90 %)

### ISSUE THREAD

**Issue by arekm** [glensc/nagios-plugin-check_raid#190]
arcconf plugin (4.0.8) doesn't handle logical device status: Impacted ( Build/Verify with fix : 90 % )

```
# /usr/lib/nagios/plugins/check_raid
Unknown line: [   Logical Device                 : 0] at /usr/share/perl5/vendor_perl/App/Monitoring/Plugin/CheckRaid/Plugins/arcconf.pm line 88, <$fh> line 3.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/vendor_perl/App/Monitoring/Plugin/CheckRaid/Plugins/arcconf.pm line 607.
UNKNOWN: arcconf:[Controller:Optimal, Logical Device #: Build/Verify with fix: In Progress 90%, Logical Device 0(STORAGE1):Impacted ( Build/Verify with fix : 90 % ), Logical Device 1(STORAGE2):Optimal, Drives: BTTV605101CU200GGN,BTTV605101GX200GGN,BTTV605100CG200GGN,NAHGY61X,NAGDP1WX,NCH2GD0Z,NCH1R41Z,NCGZJYVV,NCH2EX7Z,NAG2Y0LY,NCH2G2RZ,NCGZBTHV,NAGUKP3X,NAG41A7Y,NCH1S5MZ,NCH1S6KZ,NCH2EX3Z,NCH2G8MZ,NCGZEG3V,NCH2K6VZ,NCH2K32Z=Online]; mdstat:[md2(767.94 MiB raid1):UU, md3(185.42 GiB raid1):UU]
```
[arcconfJan-check_raid.txt](https://github.com/glensc/nagios-plugin-check_raid/files/2803079/arcconfJan-check_raid.txt)
[arcconfJan-dmsetup.txt](https://github.com/glensc/nagios-plugin-check_raid/files/2803080/arcconfJan-dmsetup.txt)
[arcconfJan-getconfig.txt](https://github.com/glensc/nagios-plugin-check_raid/files/2803081/arcconfJan-getconfig.txt)
[arcconfJan-getstatus.txt](https://github.com/glensc/nagios-plugin-check_raid/files/2803082/arcconfJan-getstatus.txt)

**Comment by csware** [comment]
I've the same issue. The reason for this is a subtle change in casing (`Logical device` -> `Logical Device` in parse_getstatus). Working on a PR.

**Comment by glensc** [comment]
correct [auto close pattern][1] was not used in https://github.com/glensc/nagios-plugin-check_raid/pull/217, so, closing manually.

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
