### ISSUE TITLE
Possible to hide "OK" results or just showing "OK" and not all devices?

### ISSUE THREAD

**Issue by JimmyBeans79** [glensc/nagios-plugin-check_raid#195]
Howdy!

I use your plugin in combination with Nagios for my big backup server and it works perfectly!
However one minor gripe... I have quite a few drives; actually I have so many that my Nagios overview screen gets "eaten" away. ;-)

It now displays the following:
`OK: tw_cli:[c0(9650SE-24M8): u0(RAID-6): OK, Cache:OFF, Drives(22): p0,p1,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p2,p20,p21,p3,p4,p5,p6,p7,p8,p9=OK, c1(9650SE-24M8): u0(RAID-6): OK, Cache:ON, Drives(22): p0,p1,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p2,p20,p21,p3,p4,p5,p6,p7,p8,p9=OK, c2(9650SE-2LP): u0(RAID-1): OK, Cache:ON, Drives(2): p0,p1=OK] `

Is it possible to "cut" down most of this information? Ofcourse only when everything is OK.
Preferred output would be something like this:

`OK: tw_cli:[c0(9650SE-24M8): u0(RAID-6): OK, Cache:OFF, Drives(22): OK, c1(9650SE-24M8): u0(RAID-6): OK, Cache:ON, Drives(22): OK, c2(9650SE-2LP): u0(RAID-1): OK, Cache:ON, Drives(2): OK]`

Maybe it is also possible to "style" the output a little, so each controller is on a new line perhaps?

_I know this is not an "issue", but since I am new to Github (never been active before) I have no idea on how to change it into a question or similar?_

**Comment by glensc** [comment]
my idea was to shorten the drive list into ranges:

```diff
-Drives(22): p0,p1,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p2,p20,p21,p3,p4,p5,p6,p7,p8,p9=OK
+Drives(22): p0-p11,p13-p20=OK
```

the reason why everything is on one line is that older Nagios showed only first line in the notification. not sure if that's the case or maybe it's limitation of nrpe and/or nrpe version.

**Comment by JimmyBeans79** [comment]
Howdy!

I completely lost track of this. Is this possible with the latest version?
Or did you mean with "limitation of nrpe and/or nrpe version" that this is not possible in general?

It's not a big thing. Normally it will not be shown anyways, when everything is "OK" obviously. I only display "problems", but stil... Looking at all services, this line makes the rest look messy in terms of output.

**Comment by glensc** [comment]
not sure what is "this" in your sentence, but the idea I wrote here is not implemented: https://github.com/glensc/nagios-plugin-check_raid/issues/195#issuecomment-503018851

**Comment by JimmyBeans79** [comment]
Howdy!

Okay good to know.
