### ISSUE TITLE
adapt check_raid to show sub-check results

### ISSUE THREAD

**Issue by calestyo** [glensc/nagios-plugin-check_raid#2]
Hi.

It would be nice if check_raid can produce output similar to what is known from e.g. check_multi: http://my-plugin.de/wiki/projects/check_multi/screenshot

That means:
The global status of check_raid should be like now, all RAIDs are checked, if any of them is not OK the status is not OK.
But additional output should be given for each RAID (of each controller), perhaps in a tree as the check_multi examples show.

Cheers
Chris.

**Comment by glensc** [comment]
this is too complex to implement. plugins should first emit data structures in common format. currently few do (have look at t/dump dir), but it's not consistent. it's long process to change all plugins, some plugins even have not been split to parse() and check() functions.
