### ISSUE TITLE
WARNING: megacli:[Volumes(1): DISK0.0:Optimal, WriteCache:DISABLED

### ISSUE THREAD

**Issue by duven87** [glensc/nagios-plugin-check_raid#202]
Hello, forgive me for writing on this issue. I would say it is not.
I just wanted to interpret the Warning of this output:

WARNING: megacli:[Volumes(1): DISK0.0:Optimal, WriteCache:DISABLED: Devices(8): 08, 09, 10, 11, 12, 14, 15, 17=Online]

I guess the warning is due to WriteCache:DISABLED. Right?
I've been looking at the plugin options and I haven't found any option to ignore this Cache and make the check OK.
Can I do something ?

**Comment by glensc** [comment]
what about this option?

```
    --cache-fail=STATE  Set status as STATE if Write Cache is present but disabled. Defaults to `WARNING`
```

**Comment by duven87** [comment]
Perfect! Thanks! too easy.. sorry
sudo /usr/lib64/nagios/plugins/check_raid --cache-fail=OK
