### ISSUE TITLE
arcconf: parse error

### ISSUE THREAD

**Issue by HOSTED-POWER** [glensc/nagios-plugin-check_raid#203]
**Output of `check_raid -d`:**

```
 ./check_raid.pl -d
check_raid 4.0.10
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs
Please include output of **ALL** commands in bugreport

DEBUG EXEC: /sbin/dmsetup status --noflush at ./check_raid.pl line 503.
DEBUG EXEC: /proc/mdstat at ./check_raid.pl line 503.
DEBUG EXEC: /usr/local/bin/arcconf GETSTATUS 1 at ./check_raid.pl line 503.
DEBUG EXEC: /usr/local/bin/arcconf GETCONFIG 1 AL at ./check_raid.pl line 503.
arcconf: parse error:    -------------------------------------------------------- at ./check_raid.pl line 699, <$fh> line 74.
arcconf: parse error:    -------------------------------------------------------- at ./check_raid.pl line 699, <$fh> line 77.
UNKNOWN: arcconf:[Controller:Optimal, Logical Device 0(DATA):Optimal, Drives: ZA27M13L,ZA26YH3Q,ZA26YHAT,ZA26YHMR,ZA26YH5A,ZA26YH3C,ZA26YM8A,ZA26YMBS,ZA26YHDH,ZA26YGZA,ZA26YH46,ZA26YHFF,ZA26YH4Z,ZA26WR4F=Online ZA26J7G0=Ready]
```

[output.txt](https://github.com/glensc/nagios-plugin-check_raid/files/6249527/output.txt)

**Comment by HOSTED-POWER** [comment]
Ok I forked it and it works fine now on our raid controllers with arcconf 2.04 and 3.04.

https://github.com/HOSTED-POWER/nagios-plugin-check_raid

If you have time, you could integrate the changes.

**Comment by glensc** [comment]
@HOSTED-POWER submit your changes as pull request

**Comment by HOSTED-POWER** [comment]
I did, but I suppose you'll have to skip the readme :)

**Comment by glensc** [comment]
this is not how the pull requests work. you have to remove the changes from the branch pull request is made from.

**Comment by MarcusCaepio** [comment]
Hi,
so will anything happen here? Having the same issue :) 
Cheers,
Marcus

**Comment by carnil** [comment]
https://github.com/glensc/nagios-plugin-check_raid/pull/210 should close this issue.
