### ISSUE TITLE
Error with P440AR RAID controller. How to solve, what to change? Please advice.

### ISSUE THREAD

**Issue by HHawk** [glensc/nagios-plugin-check_raid#214]
Hi,

Probably a very dumb question, but it's been a while since I have (re)configured Nagios and your very useful plugin script to check RAID functions and health.

So far we only had HP servers with the older RAID controller like P400 and P400i. Recentely we have purchased several newer HP servers which have the following RAID controller: P440AR.

Now Nagios reports the disks to be fine, but does report an error. The error we are getting on these newer HP server (with the P440AR RAID controller) is: UNKNOWN: hpacucli:[[ERROR, The controller must be identified by slot, chassisname, wwn,]]: ssacli:[Smart Array P440ar[OK]: Array A(OK)[LUN1:OK]]

I am guessing that I should disable "hpacucli" with these newer HP RAID controllers or should I change something? Again sorry if I am asking a dumb question, but I have no clue on how to get rid of this message, as the RAID array is fine (as reported by ssacli).

Maybe I should de-install hpacucli for these servers?

Thank you in advance.

Regards

**Comment by HHawk** [comment]
Sorry for the bump, but it would be great if someone could provide some help with this. Thanks in advance!

**Comment by csware** [comment]
Please see https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md on how to properly report issues.

**Comment by HHawk** [comment]
??

**Comment by HHawk** [comment]
A small update. Now this is the strange part. Both servers have the same RAID controller.
But when I test it like below, I get different output.

SERVER 1
[root@server1~]# /usr/lib64/nagios/plugins/check_raid.pl   -p hpacucli
check_raid UNKNOWN - No active plugins (No RAID found)
[root@server1~]# vi /etc/nagios/nrpe.cfg
[root@server1~]# /usr/lib64/nagios/plugins/check_raid
Unhandled: [       or IPF information.]
Use of uninitialized value in string ne at /usr/lib64/nagios/plugins/check_raid.pl line 3149.
UNKNOWN: hpssacli:[Slot 0 (Embedded) [ERROR, The controller must be identified by slot, serialnumber, index, first,]]; ssacli:[Smart Array P440ar[OK]: Array A(OK)[LUN1:OK]]

(this also translates into the error as I am seeing in the front-end)

But on the other server:
[root@server2~]# /usr/lib64/nagios/plugins/check_raid
OK: ssacli:[Smart Array P440ar[OK]: Array A(OK)[LUN1:OK]]

Strange. Must be some older reference related to hpssacli, right?

**Comment by HHawk** [comment]
Okay added fot the "problem" server the part:  -p ssacli
No more errors.

Sorry for your time.
