### ISSUE TITLE
mdstat plugin returns incorrect state for recovery/reshape

### ISSUE THREAD

**Issue by toddles** [glensc/nagios-plugin-check_raid#43]
When reshaping or recovering disks, the mdstat plugin returns OK for both states

recovery:

    # cat /proc/mdstat
    Personalities : [raid6] [raid5] [raid4]
    md0 : active raid6 sde1[6] sdf1[7] sdb1[0] sdg1[3] sdd1[2] sdc[1]
      5860543744 blocks level 6, 4k chunk, algorithm 2 [6/4] [UUUU__]
      [===>.................]  recovery = 19.6% (288381540/1465135936) finish=1420.1min speed=13810K/sec

    unused devices: <none>

    # ./check_raid.pl -p mdstat
    OK: mdstat:[md0(5.46 TiB raid6):UUUU__ (recovery:19.8% 13972K/sec ETA: 1400.9min)]

reshape:

    # cat /proc/mdstat
    Personalities : [raid6] [raid5] [raid4]
    md0 : active raid6 sde1[6](S) sdf1[7](S) sdb1[0] sdg1[3] sdd1[2] sdc[1]
      5860543744 blocks super 0.91 level 6, 4k chunk, algorithm 18 [6/4] [UUUU__]
      [=========>...........]  reshape = 48.4% (709745748/1465135936) finish=1271.8min speed=9898K/sec

    unused devices: <none>

    # ./check_raid.pl -p mdstat
    OK: mdstat:[md0(5.46 TiB raid6):UUUU__ (reshape:8.4% 9492K/sec ETA: 2355.1min)]

**Comment by glensc** [comment]
closing for now
