### ISSUE TITLE
Allow for plugin specific options

### ISSUE THREAD

**Issue by elconas** [glensc/nagios-plugin-check_raid#58]
Hello, 

it would be great if parameters could be passed to the plugins, eg. via GetOptionsFromString() to allow parsing extra options of the plugins. 

This would allow enabeleing, setting parameters and disabeling of plugin features (e.g. disable MegaCli BBU Monitoring). Having a general infrastrucure for this, would be great.

Regards, 
Robert

**Comment by glensc** [comment]
added `--plugin-option` argument.

the options are global, not plugin specific, but it's recommended to prefix option with plugin name.
the convention is to have `PLUGIN_NAME-OPTION_NAME=OPTION_VALUE` syntax to namespace each plugin option.

so `--plugin-option=hp_msa-serial=/dev/ttyS2` would define option `serial` for `hp_msa` plugin with value `/dev/ttyS2`.
