### ISSUE TITLE
invoke sudo only with -g root and not (implicitly) with -u root

### ISSUE THREAD

**Issue by calestyo** [glensc/nagios-plugin-check_raid#6]
Hi.

For many check binaries, it may be possible to run them as normal user (the one invoking check_raid) but only the root _group_ added.

For those for which this is known, I'd suggest to change:
- the invocation of sudo to include "-g root"
- the sudoers Runas_Spec to be "(:root)".

This tightens things a bit more at least.

I tried it for sas2ircu and it seems to work there.

Cheers,
Chris.

**Comment by boomertsfx** [comment]
We use check_raid.pl as root on Solaris which has worked well, but when we upgraded to the latest version, it now says it can't find sudo.  We don't need sudo and Solaris doesn't come stock with sudo.  Is there a way around this?

**Comment by glensc** [comment]
Create separate issue (or even PR) for your problem, don't hijack unrelated tickets.
