### ISSUE TITLE
msa1500 serial line check not working

### ISSUE THREAD

**Issue by mesb1** [glensc/nagios-plugin-check_raid#97]
Hi.
If msa1500 isn't connected via fc (serial only), check doesn't work.

We have standalone nagios machine, that have attached to msa1500 directly with com port only.
But this machine doesn't connected to it via fc, so it nothing know about it's volumes via fc and /sys/block/*/device/model.
I suppose there is sense add key forces ttyS0 checking for msa1500.
As option cool to add option for other than ttyS0, when working via usb2com it can be ttyUSB0 etc.

**Comment by mesb1** [comment]
Also machine with connected fc shows:
cat /sys/block/*/device/model
LOGICAL VOLUME
MSA1000 VOLUME

**Comment by glensc** [comment]
can you try forcing plugin:

```
./check_raid.pl -p hp_msa
```

what does it do?

**Comment by glensc** [comment]
btw there's already RFE to have plugin specific options: #58. nothing implemented yet

**Comment by mesb1** [comment]
./check_raid.pl -p hp_msa
No RAID configuration found (tried: )

**Comment by glensc** [comment]
btw, you can just write "return 1" to "sub detect" of "package hp_msa" on your nagios node having serial connected (somewhere on line 3680).

```perl
# check from /sys if there are any MSA VOLUME's present.
sub detect {
    return 1;
}
```

let me know if it works at least then

**Comment by glensc** [comment]
you should be able to set serial line and force plugin to be enabled via plugin options commandline argument:

```
./check_raid.pl -p hp_msa --plugin-option=hp_msa-serial=/dev/ttyS2 --plugin-option=hp_msa-enabled
```

**Comment by mesb1** [comment]
Nope.
I get new version via:
wget https://raw.github.com/glensc/nagios-plugin-check_raid/master/check_raid.pl -O check_raid.pl
Then:
./check_raid.pl -d -p hp_msa --plugin-option=hp_msa-serial=/dev/ttyS0 --plugin-option=hp_msa-enabled
check_raid Version 3.2.3
See CONTRIBUTING.md how to report bugs with debug data:
https://github.com/glensc/nagios-plugin-check_raid/blob/master/CONTRIBUTING.md

UNKNOWN: hp_msa:[Plugin error]

**Comment by mesb1** [comment]
I look inside and looks like it gave controller few commands:
show globals         

Global Parameters:
   System Name:        
   Rebuild Priority:   medium
   Expand Priority:    medium
   Surface Delay:      3.0 seconds

   Total Cache:        256MB
      60% Read Cache:  154MB
      40% Write Cache: 102MB

   Temperature:
          EMU: 23 Celsius,  73 Fahrenheit
          PS1: 24 Celsius,  75 Fahrenheit
          PS2: 24 Celsius,  75 Fahrenheit

CLI-1> show this_controller 
Controller 1 (right controller):
MSA1500(c) Hewlett-Packard PB9840KX3T40BP Version 5.20 Build 1500 Hardware A
Build Time: 2007-01-24 16:03:28
   Component Enclosure.
   Controller Identifier: 
   NODE_ID = 500508B3-009293D0
   SCSI_VERSION = SCSI-3
   Supported Redundancy Mode: Active/Standby Asym-Active/Active 
   Current Redundancy Mode: Not Redundant (No Failure)
   Device Port SCSI address 6
   Terminal speed for the CLI is set to 19200.
Host Port_1:
   REPORTED PORT_ID 500508B3-009293D1
   PORT_1_TOPOLOGY = F_Port
Cache:
   154 megabyte read cache   102 megabyte write cache  Version 2
   Cache is GOOD, and Cache is enabled.
   No unflushed data in cache
   Batteries are disabled
   Module #1 is fully charged and turned off.
Controller Up Time:
   122 Days 13 Hours 57 Minutes 37 Seconds
Health:
   Surface Scan:   Complete.
   Rebuild Status: Complete.
   Expansion:      Complete.

CLI-1> 

CLI-1> show other_controller
Other controller is not present or fully started.


CLI-1> exit                 
Invalid CLI command.

CLI-1>

**Comment by glensc** [comment]
followup issue created #102
